WebsiteDNSName:
  Type: AWS::Route53::RecordSetGroup
  Properties:
    HostedZoneName:
      Fn::Join:
        - ''
        - - ${self:custom.domain}
          - .
    RecordSets:
      - Name: ${self:custom.fullDomainName}
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt [WebsiteCloudfront, DomainName]
      - Name: ${self:custom.fullDomainName}
        Type: AAAA
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt [WebsiteCloudfront, DomainName]
