service:
  name: angular-lodewijkwensveen-database
org: lwensveen
app: angular-lodewijkwensveen-resources

custom: ${file(../../serverless.common.yml):custom}

provider:
  name: aws
  region: eu-west-1
  stage: dev
  runtime: nodejs12.x

  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

resources:
  Resources:
    ContentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: contentId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: contentId
            KeyType: RANGE
        # Set the capacity based on the stage
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}

  # Print out the name of the table that is created
  Outputs:
    ContentTableName:
      Value:
        Ref: ContentTable
