service:
  name: uploads
org: lwensveen
app: lodewijkwensveen-resources

provider:
  name: aws
  region: eu-west-1
  stage: dev
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

resources:
  Resources:
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: 'react.lodewijkwensveen.nl'
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: 404.html
    WebsiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref 'WebsiteBucket'
        PolicyDocument:
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: s3:GetObject
              Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WebsiteBucket', /*]]
  Outputs:
    BucketName:
      Value: !Ref 'WebsiteBucket'
      Description: Name of S3 bucket to hold website content
