service:
  name: react-hosting
org: lwensveen
app: lodewijkwensveen-resources

custom: ${file(../../../serverless.common.yml):custom}

provider:
  name: aws
  region: eu-west-1
  stage: dev
  runtime: nodejs12.x
  cfnRole: ${self:custom.cfnRole}

resources:
  # Cloudfront
  - ${file(./cloudfront/cloudfront.yml)}
  # Route53
  - ${file(./route53/route53.yml)}
