service:
  name: websitebucket
org: lwensveen
app: lodewijkwensveen-resources

custom: ${file(../../../serverless.common.yml):custom}

provider:
  name: aws
  region: eu-west-1
  stage: dev
  runtime: nodejs12.x
  cfnRole: ${self:custom.cfnRole}

resources:
  Resources:
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.fullDomainName}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: 404.html
    WebsiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref 'WebsiteBucket'
        PolicyDocument:
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: s3:GetObject
              Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WebsiteBucket', /*]]
  Outputs:
    BucketName:
      Value: !Ref 'WebsiteBucket'
      Description: Name of S3 bucket to hold website content
